name: crawler_blog

on:
  push:
    branches:
      - master # 或者你使用的分支
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # 使用合适的 Node.js 版本

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 构建 VitePress 网站
      - name: Build VitePress site
        run: npm run build

  algolia:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 安装 Algolia 爬虫依赖
      - name: Install dependencies
        run: npm install

      # 运行 Algolia 爬虫（确保你的 crawlerConfig.json 配置正确）
      - name: Trigger Algolia Crawler
        run: |
          curl -sL https://github.com/algolia/algoliasearch-website-crawler/releases/download/v1.0.0/algolia-crawler-linux-amd64-1.0.0.tar.gz | tar xz
          ./algolia-crawler --config crawlerConfig.json
